jenkins-x/bdd-jx

- Makefile
- Readme.md
- jx_test_app.go
- main.go
This PR adds support for testing:
- `jx add app`
- `jx delete app`
To run a once off test using a known version of the jacoco app you can run: `make test-app-lifecycle`
To run a test against multiple apps and versions you use the following syntax: `JX_BDD_INCLUDE_APPS=jx-app-jacoco:0.0.100,my-app:0.0.1 make test-app`
> feat: Add app tests

- main.go
`CreateAuthConfigService` expects to be given a path relative to the config path and then the config has to be explicitly loaded.
> Load config from gitAuth.yaml

- jx_create_quickstart_android_quickstart.go
- jx_create_quickstart_angular_io_quickstart.go
- jx_create_quickstart_aspnet_app.go
- jx_create_quickstart_open_liberty.go
- jx_create_quickstart_spring_boot_http_gradle.go
- jx_create_quickstart_spring_boot_rest_prometheus.go
- jx_create_quickstart_vertx_rest_prometheus.go
- jx_create_spring.go
- jx_import.go
- main.go
update the code to reflect this.
Whilst most of this is cosmetic, the commands to run `jx delete app` are now out of date and failing (because the command used to be `jx delete app` (meaning delete an application) but has now changed to be `jx delete application` so as not to conflict with the entirely different `jx delete app` (meaning delete a platform addon) command.
The main cause of this was at the end of the tests, the cleanup code did `jx delete app <appname> -b` and resulted in `Error: unknown shorthand flag: 'b' in -b` because `jx delete app` has a new meaning.
> bug(applications): the meaning of 'app' and 'application' changed

- Makefile
- jx_verify_pods.go
Adding test step to verify that there are no failed pods after. This should catch the issue when CronJobs fail during the BDD test run.
> feat: Add step to verify no failed pods

- test/spring/jx_create_spring.go
This fixes the `bdd` context on `jx` that was broken by https://github.com/jenkins-x/bdd-jx/pull/45, by letting us disable manual promotion for just that run.
/assign @fiunchinho 
/assign @jstrachan
> fix: Skip manual promotion if env var is set.

- Makefile
So `node-http-watch-pipeline-activity` fails with
```
> REPLACE_ME@1.0.0 start /usr/src/app
> node server.js
/usr/src/app/server.js:48
ct = moment(object.object.metadata.creationTimestamp);
^
TypeError: Cannot read property 'metadata' of undefined
at module.exports.JSONStream.jsonStream.on.object (/usr/src/app/server.js:48:29)
at module.exports.JSONStream.emit (events.js:180:13)
at addChunk (_stream_readable.js:274:12)
at readableAddChunk (_stream_readable.js:261:11)
at module.exports.JSONStream.Readable.push (_stream_readable.js:218:10)
at module.exports.JSONStream.Transform.push (_stream_transform.js:146:32)
at module.exports.JSONStream.JSONStream._transform (/usr/src/app/node_modules/json-stream/lib/json-stream.js:32:14)
at module.exports.JSONStream.Transform._read …
```
> fix: node-http-watch-pipeline-activity is broken, use node-http instead

- Makefile
This import is clashing in the BDD tests for CJXD. Removing because it's redundant as it tests the same as `golang-http`.
> feat: remove redundant import

- Makefile
This is needed because some BDD tests are failing with:
```
JX_BDD_QUICKSTARTS= GO111MODULE=on go test -v -timeout 2h ./test/suite/quickstart -ginkgo.focus=(node-http|spring-boot-http-gradle|golang-http)
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `JX_BDD_QUICKSTARTS= GO111MODULE=on go test -v -timeout 2h ./test/suite/quickstart -ginkgo.focus=(node-http|spring-boot-http-gradle|golang-http)'
```
> fix: a fix to ginkgo-focus syntax

- test/helpers/suite.go
- test/helpers/test.go
We disabled the default reporter so we are not getting things like: 
```
Ran 4 of 4 Specs in 1462.171 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSuite (1462.17s)
PASS
```
And added a fix to set the WorkDir variable.
> fix: set the correct WorkDir and enable default reporter again for better feedback

- Makefile
`-ginkgo.focus=golang-http` results in both `golang-http` and
`golang-http-from-jenkins-x-yml` being run, since `-ginkgo.focus` is
doing a regex match. I think this should keep it from doing that.
> fix: test-quickstart-golang-http should just run one quickstart

- test/suite/quickstart/helpers.go
Ginkg's focus' regex is matching too many elements right now, as it seems to match on "contains" rather than exact matches.
This should limit the quickstarts that it uses for now.
> feat: hardcode supported quickstarts until we find a fix for ginkgo's focus matching too many items

- Makefile
Argh, this didn't work and in fact broke everything.
Reverts jenkins-x/bdd-jx#75
> Revert "fix: test-quickstart-golang-http should just run one quickstart"

- Makefile
It'll run with the focus on whatever the value of
`${BDD_TEST_SINGLE_IMPORT}` is set to. This will let us change the
`jenkins-x-versions` tests to run individual imports in different
contexts, which will speed up the `tekton` context (currently the long
poll for the `jenkins-x-versions` PR tests to finish) by having it
only run one import while, say, `boot-local`, `boot-vault`, and `ng`
each run one of the three imports.
> chore: Add target for running a single import

- test/helpers/test.go
- test/utils/runner/runner.go
when we don't need a timeout value to avoid losing the actual error message
> fix: lets add a simpler function to invoke commands

- jenkins-x-release.yml
- jenkins-x.yml
- jx/bdd/README.md
- jx/bdd/ci.sh
- jx/bdd/cluster.yaml
- jx/bdd/jx-requirements.yml
- jx/bdd/parameters.yaml
Also adds `jenkins-x-release.yml`, which we'll need once https://github.com/jenkins-x/environment-tekton-weasel-dev/pull/273 is merged.
fixes #6116
> fix: Run BDD tests against a fresh cluster for bdd-jx PRs

- test/suite/quickstart/helpers.go
This PR is part of the broader outlined in https://github.com/jenkins-x/lighthouse/issues/64 and specifically addresses https://github.com/jenkins-x/lighthouse/issues/185 and https://github.com/jenkins-x/lighthouse/issues/186. 
These are a first attempt at testing the /approve and /lgtm ChatOps commands.
Fixes https://github.com/jenkins-x/lighthouse/issues/185
Fixes https://github.com/jenkins-x/lighthouse/issues/186
> feat(prow): Add BDD tests for ChatOps commands

- jenkins-x.yml
- jx/bdd/ci.sh
- test/suite/upgrade/upgrade_boot.go
This PR makes the binary override  optional and the upgrade ref configurable when running the upgrade boot bdd test
> chore: make the upgrade ref and binary overwrite 

- Makefile
Disabling chatops commands testing because it doesn't really provide a lot of value and it's causing issues for some BDD tests.
> feat: disable chatops commands testing

- test/suite/_import/jx_import.go
The `golang-http-from-jenkins-x-yml` quickstart has a hardcoded `gcr.io` url and we'll need to modify the jx binary to make it work with EKS.
> feat: disable the import with a jenkins-x file as it's hardcoded to push to GCR

- Makefile
This is a temporary change so we can debug which git credentials are being used.
> chore: displaying the git-credentials to the console

- test/helpers/test.go
- test/utils/parsers/get_applications_parser.go
I see this show up once in a while in BDD tests, resulting in:
```
Unexpected error:
<*url.Error | 0xc000264030>: {
Op: "Get",
URL: "1/1",
Err: {
what: "unsupported protocol scheme",
str: "",
},
}
Get 1/1: unsupported protocol scheme ""
occurred
```
So let's try to deal with that by both logging the full output when
this happens, and retrying.
> chore: Keep retrying if the application URL is "1/1"

- test/utils/parsers/create_pull_request_parser.go
It's like
`https://gitlab.com/jxbdd/bdd-spring-1580224566/-/merge_requests/1`
now - that `-/` is throwing things off here. Handling inside jx proper
is just fine, it's only the parsing in `ParseJxCreatePullRequest` here
that's failing.
fixes https://github.com/jenkins-x/jx/issues/6618
> fix: Gitlab merge request URL format has changed

- test/utils/parsers/get_applications_parser.go
Sigh, `url.Parse` doesn't error out on `"1/1"`, defeating the purpose
to some extent. =) So let's also make sure the result's scheme is
non-empty.
> fix: Don't just parse app URL, check for non-empty scheme

- test/helpers/suite.go
- test/helpers/test.go
Specifically for use with static master BDD tests. Also cleans up some
debug logging I forgot to delete.
> fix: Allow disabling PipelineActivity update check

- Makefile
so we can run the bdd tests from a binary without needing to build it every time we run it
> fix: add a `testbin` goal to create a bddjx binary

- jx/bdd/jx-requirements.yml
- jx/bdd/parameters.yaml
- test/helpers/test.go
- test/suite/apps/ui.go
- test/suite/jxui/jxui.go
- test/utils/parsers/create_pull_request_parser.go
I've tested this with `test-app-lifecycle` and it worked, so hopefully I didn't do something magic in my test environment. =)
Ideally, I'd like to do this with the upgrade boot test too, but I'll come back to that - there's no `--auto-merge` flag there, so it would need to have a `/approve` added, which may not work quite right with the bot user. I'll loop back on that.
fixes https://github.com/jenkins-x/jx/issues/6850
> fix: Tide should be merging PRs we have been merging manually in tests

- Makefile
- go.sum
- test/helpers/test.go
- test/suite/lighthouse/helpers.go
- test/suite/lighthouse/lighthouse_test.go
- test/suite/quickstart/helpers.go
I also moved the existing chatops tests to the new `test/suites/lighthouse/helpers.go` to centralize the LH/chatops tests, and I'll eventually add more tests to this for multiple contexts, both required and optional, but this is a start.
I'm validating the new `test-lighthouse` target on the `github` context on https://github.com/jenkins-x/lighthouse/pull/578
fixes https://github.com/jenkins-x/jx/issues/6862
> fix: Add Lighthouse/Prow test for retest and override

- go.mod
- go.sum
- jx/bdd/ci.sh
- test/helpers/test.go
- test/suite/lighthouse/helpers.go
- test/suite/saas/jx_saas.go
Required some changes in jx, disabling a couple things if GitLab, and using `/lh-approve` and `/lh-assign` instead of `/approve` and `/assign` to sneak around GitLab quick actions hijacking.
> fix: Get Lighthouse tests to work on GitLab

- test/suite/jxui/jxui.go
- test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
- test/suite/jxui/ui-smoke/get-free-port.js
- test/suite/jxui/ui-smoke/package-lock.json
- test/suite/jxui/ui-smoke/package.json
- test/suite/jxui/ui-smoke/proxy.js
- test/suite/jxui/ui-smoke/run.sh
* Ensures that JXUI is basic auth secured when `JX_APP_UI_TEST_BASIC_AUTH=true` is set.
* Runs Cypress tests against a local JS proxy that injects the basic auth credentials into all JXUI requests (in run.sh - this was not (easily) possible with Cypress itself since it does not pass through basic auth credentials to websocket requests).
relates to/blocks:
* https://github.com/cloudbees/jxui-frontend/issues/1490
* https://github.com/cloudbees/jxui-frontend/pull/1491
> feat: Support basic auth protected JXUI

- test/suite/jxui/jxui.go
Now that JXUI is basic auth secured by default we need to provide the credentials while accessing it during tests by default.
Otherwise all builds that don't explicitly set `JX_APP_UI_TEST_BASIC_AUTH=true` will fail.
cc @romainverduci
> fix: assume jxui basic auth by default

- Makefile
Adds make commands to run single import/quickstart tests, we plan on reusing those tests to speed up the downstream CJXD tests. Could also be used to speed up upstream jx tests.
Part of work to fix https://github.com/cloudbees/cloudbees-jenkins-x-distro/issues/196
> chore: Add make commands for single quickstart/import tests

- go.mod
- go.sum
> fix: Workarounds for go modules that don't download in athens
