- OWNERS
> feat: Add OWNERS file

- main.go
Reverts parts of 89ad36a2ec4ec6161cfda34278acefafaf014fd2
> fix: increase timeout to 20 mins for promotion

- Makefile
- apps.go
- bdd_jx_suite_test.go
- go.mod
- go.sum
- main.go
There are several things going on this PR. This is very much a WIP and I'm only creating this PR so I have somewhere to discuss things.
Rather than relying on args.Parse to try and decide what tests are going to be added, I've changed it to use environment variables. There are some weird interactions going on because gingko uses args.Parse as well. If bdd-jx was just using args at test runtime I think there would be no issue, rather than during the setup phase.
It would be possible to still use `os.Args` with another library but I think Env is fine for what is needed. 
This PR relies on https://github.com/jenkins-x/jx/pull/3349 to be merged. I also moved app specific test code into its own file for readability reasons.
> Update app tests 

- apps.go
- jx_create_spring.go
- jx_import.go
- jx_upgrade_ingress.go
- jx_upgrade_platfrom.go
- jx_verify_pods.go
- main.go
- runner/runner.go
- utils/utils.go
Note: need to refactor some assertions to use commands not imports
> Feat: instrument commands with coverage

- test/helpers/test.go
- test/spring/jx_create_spring.go
Changes being tested here https://github.com/jenkins-x/jx/pull/4793
> feat: Manually promote application to production on create spring scenario

- Makefile
- test/_import/suite_test.go
- test/apps/suite_test.go
- test/quickstart/suite_test.go
- test/spring/suite_test.go
- test/step/suite_test.go
Changed the suite names so they make sense in the generated HTML report.
Also created a new quickstarts goal to group them up for better visualization in the HTML report.
> feat: modify suite names and create a new quickstarts goal

- Makefile
Fix so the goal is actually executable
> fix: fix the goal so it's executable

- test/utils/parsers/create_pull_request_parser.go
> fix: use a more flexible regex for parsing PR URLs

- Makefile
Tested in https://github.com/jenkins-x/jx/pull/4847, passes, makes me very happy. =)
/assign @dgozalo 
/assign @fiunchinho
> chore: Add import test for a project with a multi-stage jenkins-x.yml

- test/helpers/test.go
> fix: actually re-run the `jx get activities` code in the retry

- test/helpers/test.go
lets use regular errors to avoid the retry stopping early
> fix: try fix the retry in the preview tests for meta pipeline

- test/helpers/test.go
and it doesn't terminate too early
> fix: lower the timeouts now we know the retry works

- test/helpers/test.go
which uses different URLs for PR URLs
> fix: handle finding preview URL for bitbucket server

- test/helpers/suite.go
- test/helpers/test.go
- test/suite/quickstart/helpers.go
First of three tests for prow ChatOps commands, this one being the test for the assign plugin.
> feat(prow): test prow's assign ChatOps command

- test/helpers/suite.go
- test/helpers/test.go
- test/suite/quickstart/helpers.go
> fix: Revert "feat(prow): test prow's assign ChatOps command"

- .gitignore
- Readme.md
- test/suite/jxui/Readme.md
- test/suite/jxui/jxui.go
- test/utils/runner/runner.go
As discussed with @romainverduci it would be handy while running JXUI test suite to be able to point to a local install and skip some of the jxui-app installation
> Jxui dev mode

- test/suite/jxui/jxui.go
Improve test code by reorganising test setup and actual test, output:
- Have only 1 ginkgo test in the report (running UI Smoke tests)
- Simplify test setup and combine the different BeforeEach
Has been running in https://github.com/cloudbees/jxui-frontend/pull/1091 build `#2 end-to-end`
> chore: reorganise jxui test code

- go.mod
- go.sum
- test/helpers/suite.go
- test/helpers/test.go
> chore: Enable chatops tests explicitly only

- test/helpers/test.go
Testing for non-boot scenarios with https://github.com/jenkins-x/jx/pull/6731
fixes https://github.com/jenkins-x/jx/issues/6738
> fix: Test for PR PipelineActivity being populated by build controller

- Makefile
> revert: stop setting the credentials helper to store

- OWNERS
- test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
The fix has been validated in https://github.com/cloudbees/jxui-frontend/pull/1213
> test: update search test to match the new behaviour

- test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
fixes https://github.com/cloudbees/jxui-frontend/issues/1225
> fix: update build search test to no validate the exact number of builds filtered

- test/helpers/suite.go
- test/helpers/test.go
> chore: Add testing of Lighthouse status report link

- test/helpers/test.go
> fix: Forgot about pointers

- test/helpers/test.go
- test/suite/lighthouse/helpers.go
Relates to https://github.com/jenkins-x/lighthouse/issues/708
> chore: Add cc/uncc test for Lighthouse

- go.mod
- go.sum
> chore: Bump jx version

- jx/bdd/ci.sh
> fix: Copy jx dependencies into temp JX_HOME in test run

- test/helpers/test.go
- test/suite/lighthouse/helpers.go
> chore: Test "jx get build logs" on completed builds in Lighthouse test

- OWNERS
- test/helpers/test.go
- test/suite/apps/ui.go
- test/suite/jxui/jxui.go
And rework to have common vars for the env vars used in both cases.
Also adds @mgoltzsche to OWNERS. =)
> fix: Support basic auth with UI for apps test as well

- test/helpers/test.go
- test/suite/lighthouse/helpers.go
Validating this on https://github.com/jenkins-x/lighthouse/pull/791
> chore: Add test for OWNERS link in Lighthouse

- test/helpers/test.go
as it can take a few minutes for the PR to go green
> fix: don't fail a BDD test if the promote is not yet succeeded
